apiVersion: v1
kind: Service
metadata:
  name: detect-cracks-signs
spec:
  type: NodePort
  selector:
    app: detect-cracks-signs
  ports:
    - port: 8000
      nodePort: 30800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detect-cracks-signs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detect-cracks-signs
  template:
    metadata:
      labels: 
        app: detect-cracks-signs
    spec:
      containers:
        - name: detect-cracks-signs
          image: tabetanthony/industrial_ai_finalproject_v1:detect-cracks-signs
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: MERGED_CRACK_DETECTION_URL
              value: "http://detect-building-cracks:8001/BuildingCrackDetection"
            - name: ROAD_CRACK_DETECTION_URL
              value: "http://detect-road-cracks:8002/RoadCrackDetection"
            - name: ROAD_TRAFFIC_SIGN_DETECTION_URL
              value: "http://detect-road-traffic-signs:8003/TrafficSignDetection"

---
apiVersion: v1
kind: Service
metadata:
  name: detect-building-cracks
spec:
  type: NodePort
  selector:
    app: detect-building-cracks
  ports:
    - port: 8001
      nodePort: 30801
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detect-building-cracks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detect-building-cracks
  template:
    metadata:
      labels:
        app: detect-building-cracks
    spec:
      containers:
        - name: detect-building-cracks
          image: tabetanthony/industrial_ai_finalproject_v1:detect-building-cracks
          stdin: true
          tty: true
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: building-cracks-volume
              mountPath: /app/building_crack_detection/static/
          env:
            - name: PORT
              value: "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: detect-road-cracks
spec:
  type: NodePort
  selector:
    app: detect-road-cracks
  ports:
    - port: 8002
      nodePort: 30802
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detect-road-cracks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detect-road-cracks
  template:
    metadata:
      labels:
        app: detect-road-cracks
    spec:
      containers:
        - name: detect-road-cracks
          image: tabetanthony/industrial_ai_finalproject_v1:detect-road-cracks
          stdin: true
          tty: true
          ports:
            - containerPort: 8002
          volumeMounts:
            - name: road-cracks-volume
              mountPath: /app/road_crack_detection/static/
          env:
            - name: PORT
              value: "8002"
---
apiVersion: v1
kind: Service
metadata:
  name: detect-road-traffic-signs
spec:
  type: NodePort
  selector:
    app: detect-road-traffic-signs
  ports:
    - port: 8003
      nodePort: 30803
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detect-road-traffic-signs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detect-road-traffic-signs
  template:
    metadata:
      labels:
        app: detect-road-traffic-signs
    spec:
      containers:
        - name: detect-road-traffic-signs
          image: tabetanthony/industrial_ai_finalproject_v1:detect-road-traffic-signs
          stdin: true
          tty: true
          ports:
            - containerPort: 8003
          volumeMounts:
            - name: traffic-signs-volume
              mountPath: /app/road_traffic_sign_detection/static/
          env:
            - name: PORT
              value: "8003"
