apiVersion: v1
kind: Service
metadata:
  name: detect-crack-signs
spec:
  type: NodePort
  selector:
    app: detect-crack-signs
  ports:
    - port: 5000
      nodePort: 30500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detect-crack-signs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detect-crack-signs
  template:
    metadata:
      labels:
        app: detect-crack-signs
    spec:
      containers:
        - name: detect-crack-signs
          image: FinalProject/solution-detect-crack-signs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MERGED_CRACK_DETECTION_URL
              value: "http://127.0.0.1:5001/BuildingCrackDetection"
            - name: ROAD_CRACK_DETECTION_URL
              value: "http://127.0.0.1:5002/RoadCrackDetection"
            - name: ROAD_TRAFFIC_SIGN_DETECTION_URL
              value: "http://127.0.0.1:5003/TrafficSignDetection"
---
apiVersion: v1
kind: Service
metadata:
  name: detect-building-crack-api
spec:
  type: NodePort
  selector:
    app: detect-building-crack-api
  ports:
    - port: 5001
      nodePort: 30501
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detect-building-crack-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detect-building-crack-api
  template:
    metadata:
      labels:
        app: detect-building-crack-api
    spec:
      containers:
        - name: detect-building-crack-api
          image: FinalProject/solution-detect-building-crack-api:latest
          stdin: true
          tty: true
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
---
apiVersion: v1
kind: Service
metadata:
  name: detect-road-crack-api
spec:
  type: NodePort
  selector:
    app: detect-road-crack-api
  ports:
    - port: 5002
      nodePort: 30502
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detect-road-crack-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detect-road-crack-api
  template:
    metadata:
      labels:
        app: detect-road-crack-api
    spec:
      containers:
        - name: detect-road-crack-api
          image: FinalProject/solution-detect-road-crack-api:latest
          stdin: true
          tty: true
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"
---
apiVersion: v1
kind: Service
metadata:
  name: detect-road-sign-api
spec:
  type: NodePort
  selector:
    app: detect-road-sign-api
  ports:
    - port: 5003
      nodePort: 30503
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detect-road-sign-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detect-road-sign-api
  template:
    metadata:
      labels:
        app: detect-road-sign-api
    spec:
      containers:
        - name: detect-road-sign-api
          image: zaka4ai/solution-detect-road-sign-api:latest
          stdin: true
          tty: true
          ports:
            - containerPort: 5003
          env:
            - name: PORT
              value: "5003"