apiVersion: v1
kind: Service
metadata:
  name: detect-cracks-signs
spec:
  type: NodePort
  selector:
    app: detect-cracks-signs
  ports:
    - port: 8000
      nodePort: 30800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detect-cracks-signs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detect-cracks-signs
  template:
    metadata:
      labels: 
        app: detect-cracks-signs
    spec:
      containers:
        - name: detect-cracks-signs
          image: tabetanthony/industrial_ai_finalproject_v1:detect-cracks-signs
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: MERGED_CRACK_DETECTION_URL
              value: "http://127.0.0.1:8001/BuildingCrackDetection"
            - name: ROAD_CRACK_DETECTION_URL
              value: "http://127.0.0.1:8002/RoadCrackDetection"
            - name: ROAD_TRAFFIC_SIGN_DETECTION_URL
              value: "http://127.0.0.1:8003/TrafficSignDetection"
---
apiVersion: v1
kind: Service
metadata:
  name: building_crack_detection
spec:
  type: NodePort
  selector:
    app: building_crack_detection
  ports:
    - port: 8001
      nodePort: 30801
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: building_crack_detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: building_crack_detection
  template:
    metadata:
      labels:
        app: building_crack_detection
    spec:
      containers:
        - name: building_crack_detection
          image: tabetanthony/industrial_ai_finalproject_v1:detect-building-cracks
          stdin: true
          tty: true
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: road_crack_detection
spec:
  type: NodePort
  selector:
    app: road_crack_detection
  ports:
    - port: 8002
      nodePort: 30802
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: road_crack_detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: road_crack_detection
  template:
    metadata:
      labels:
        app: road_crack_detection
    spec:
      containers:
        - name: road_crack_detection
          image: tabetanthony/industrial_ai_finalproject_v1:detect-road-cracks
          stdin: true
          tty: true
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              value: "8002"
---
apiVersion: v1
kind: Service
metadata:
  name: road_traffic_sign_detection
spec:
  type: NodePort
  selector:
    app: road_traffic_sign_detection
  ports:
    - port: 8003
      nodePort: 30803
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: road_traffic_sign_detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: road_traffic_sign_detection
  template:
    metadata:
      labels:
        app: road_traffic_sign_detection
    spec:
      containers:
        - name: road_traffic_sign_detection
          image: tabetanthony/industrial_ai_finalproject_v1:detect-road-traffic-signs
          stdin: true
          tty: true
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              value: "8003"